name: "artifactory dokcer publish"
description: "Uploads artifact to dockerhub"

outputs:
  url:
    description: "artifact url"

inputs:
  host:
    description: 'Artifactory hostname'
    required: true
  username:
    description: 'Artifactory username'
    required: true
  password:
    description: 'Artifactory password'
    required: true
  path:
    description: 'Artifact path'
    required: true
  name:
    description: 'Artifact name'
    required: true
  version:
    description: 'Artifact version'
    required: true
  dockerfile:
    description: 'Path of the Dockerfile'
    required: false
  context:
    description: 'Docker build context'
    required: false
  tycho:
    description: 'Tycho file path'
    required: true
    default: './tycho.yaml'
  provisioning:
    description: 'Provisioning directory path'
    required: true
    default: './provisioning'
  skipProvisioning:
    description: 'Skip provisioning publish'
    required: false
  buildArgs:
    description: 'Multiline string with build args of the form ARG=VALUE'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: refresh-cw
  color: blue